services:
  embedding-service:
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8888:8888"
    volumes:
      - model_cache:/app/model_cache

    restart: unless-stopped

volumes:
  model_cache:
